/* tslint:disable */
/* eslint-disable */
/**
 * assignment-template
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookInfo
 */
export interface BookInfo {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof BookInfo
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof BookInfo
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof BookInfo
     */
    author: string;
    /**
     * 
     * @type {string}
     * @memberof BookInfo
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof BookInfo
     */
    price: number;
    /**
     * 
     * @type {string}
     * @memberof BookInfo
     */
    image: string;
    /**
     * 
     * @type {number}
     * @memberof BookInfo
     */
    stock?: number;
}

/**
 * Check if a given object implements the BookInfo interface.
 */
export function instanceOfBookInfo(value: object): value is BookInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    return true;
}

export function BookInfoFromJSON(json: any): BookInfo {
    return BookInfoFromJSONTyped(json, false);
}

export function BookInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookInfo {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'name': json['name'],
        'author': json['author'],
        'description': json['description'],
        'price': json['price'],
        'image': json['image'],
        'stock': json['stock'] == null ? undefined : json['stock'],
    };
}

export function BookInfoToJSON(json: any): BookInfo {
    return BookInfoToJSONTyped(json, false);
}

export function BookInfoToJSONTyped(value?: BookInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'name': value['name'],
        'author': value['author'],
        'description': value['description'],
        'price': value['price'],
        'image': value['image'],
        'stock': value['stock'],
    };
}

