/* tslint:disable */
/* eslint-disable */
/**
 * assignment-template
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBookBody
 */
export interface CreateBookBody {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof CreateBookBody
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateBookBody
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof CreateBookBody
     */
    price: number;
    /**
     * 
     * @type {string}
     * @memberof CreateBookBody
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CreateBookBody
     */
    author: string;
    /**
     * 
     * @type {string}
     * @memberof CreateBookBody
     */
    image: string;
}

/**
 * Check if a given object implements the CreateBookBody interface.
 */
export function instanceOfCreateBookBody(value: object): value is CreateBookBody {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    return true;
}

export function CreateBookBodyFromJSON(json: any): CreateBookBody {
    return CreateBookBodyFromJSONTyped(json, false);
}

export function CreateBookBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBookBody {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'price': json['price'],
        'description': json['description'],
        'author': json['author'],
        'image': json['image'],
    };
}

export function CreateBookBodyToJSON(json: any): CreateBookBody {
    return CreateBookBodyToJSONTyped(json, false);
}

export function CreateBookBodyToJSONTyped(value?: CreateBookBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'name': value['name'],
        'price': value['price'],
        'description': value['description'],
        'author': value['author'],
        'image': value['image'],
    };
}

