/* tslint:disable */
/* eslint-disable */
/**
 * assignment-template
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrder200Response
 */
export interface CreateOrder200Response {
    /**
     * 
     * @type {string}
     * @memberof CreateOrder200Response
     */
    orderId: string;
}

/**
 * Check if a given object implements the CreateOrder200Response interface.
 */
export function instanceOfCreateOrder200Response(value: object): value is CreateOrder200Response {
    if (!('orderId' in value) || value['orderId'] === undefined) return false;
    return true;
}

export function CreateOrder200ResponseFromJSON(json: any): CreateOrder200Response {
    return CreateOrder200ResponseFromJSONTyped(json, false);
}

export function CreateOrder200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrder200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['orderId'],
    };
}

export function CreateOrder200ResponseToJSON(json: any): CreateOrder200Response {
    return CreateOrder200ResponseToJSONTyped(json, false);
}

export function CreateOrder200ResponseToJSONTyped(value?: CreateOrder200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orderId': value['orderId'],
    };
}

