/* tslint:disable */
/* eslint-disable */
/**
 * assignment-template
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrderBody
 */
export interface CreateOrderBody {
    [key: string]: any | any;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateOrderBody
     */
    books: Array<string>;
}

/**
 * Check if a given object implements the CreateOrderBody interface.
 */
export function instanceOfCreateOrderBody(value: object): value is CreateOrderBody {
    if (!('books' in value) || value['books'] === undefined) return false;
    return true;
}

export function CreateOrderBodyFromJSON(json: any): CreateOrderBody {
    return CreateOrderBodyFromJSONTyped(json, false);
}

export function CreateOrderBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrderBody {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'books': json['books'],
    };
}

export function CreateOrderBodyToJSON(json: any): CreateOrderBody {
    return CreateOrderBodyToJSONTyped(json, false);
}

export function CreateOrderBodyToJSONTyped(value?: CreateOrderBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'books': value['books'],
    };
}

