/* tslint:disable */
/* eslint-disable */
/**
 * assignment-template
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FulfillmentItem } from './FulfillmentItem';
import {
    FulfillmentItemFromJSON,
    FulfillmentItemFromJSONTyped,
    FulfillmentItemToJSON,
    FulfillmentItemToJSONTyped,
} from './FulfillmentItem';

/**
 * 
 * @export
 * @interface FulfillOrderBody
 */
export interface FulfillOrderBody {
    [key: string]: any | any;
    /**
     * 
     * @type {Array<FulfillmentItem>}
     * @memberof FulfillOrderBody
     */
    fulfillment: Array<FulfillmentItem>;
}

/**
 * Check if a given object implements the FulfillOrderBody interface.
 */
export function instanceOfFulfillOrderBody(value: object): value is FulfillOrderBody {
    if (!('fulfillment' in value) || value['fulfillment'] === undefined) return false;
    return true;
}

export function FulfillOrderBodyFromJSON(json: any): FulfillOrderBody {
    return FulfillOrderBodyFromJSONTyped(json, false);
}

export function FulfillOrderBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): FulfillOrderBody {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'fulfillment': ((json['fulfillment'] as Array<any>).map(FulfillmentItemFromJSON)),
    };
}

export function FulfillOrderBodyToJSON(json: any): FulfillOrderBody {
    return FulfillOrderBodyToJSONTyped(json, false);
}

export function FulfillOrderBodyToJSONTyped(value?: FulfillOrderBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'fulfillment': ((value['fulfillment'] as Array<any>).map(FulfillmentItemToJSON)),
    };
}

