/* tslint:disable */
/* eslint-disable */
/**
 * assignment-template
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FulfillmentItem
 */
export interface FulfillmentItem {
    /**
     * 
     * @type {string}
     * @memberof FulfillmentItem
     */
    book: string;
    /**
     * 
     * @type {string}
     * @memberof FulfillmentItem
     */
    shelf: string;
    /**
     * 
     * @type {number}
     * @memberof FulfillmentItem
     */
    numberOfBooks: number;
}

/**
 * Check if a given object implements the FulfillmentItem interface.
 */
export function instanceOfFulfillmentItem(value: object): value is FulfillmentItem {
    if (!('book' in value) || value['book'] === undefined) return false;
    if (!('shelf' in value) || value['shelf'] === undefined) return false;
    if (!('numberOfBooks' in value) || value['numberOfBooks'] === undefined) return false;
    return true;
}

export function FulfillmentItemFromJSON(json: any): FulfillmentItem {
    return FulfillmentItemFromJSONTyped(json, false);
}

export function FulfillmentItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): FulfillmentItem {
    if (json == null) {
        return json;
    }
    return {
        
        'book': json['book'],
        'shelf': json['shelf'],
        'numberOfBooks': json['numberOfBooks'],
    };
}

export function FulfillmentItemToJSON(json: any): FulfillmentItem {
    return FulfillmentItemToJSONTyped(json, false);
}

export function FulfillmentItemToJSONTyped(value?: FulfillmentItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'book': value['book'],
        'shelf': value['shelf'],
        'numberOfBooks': value['numberOfBooks'],
    };
}

