/* tslint:disable */
/* eslint-disable */
/**
 * assignment-template
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetBookStock200Response
 */
export interface GetBookStock200Response {
    /**
     * 
     * @type {number}
     * @memberof GetBookStock200Response
     */
    stock: number;
    /**
     * 
     * @type {string}
     * @memberof GetBookStock200Response
     */
    bookId: string;
}

/**
 * Check if a given object implements the GetBookStock200Response interface.
 */
export function instanceOfGetBookStock200Response(value: object): value is GetBookStock200Response {
    if (!('stock' in value) || value['stock'] === undefined) return false;
    if (!('bookId' in value) || value['bookId'] === undefined) return false;
    return true;
}

export function GetBookStock200ResponseFromJSON(json: any): GetBookStock200Response {
    return GetBookStock200ResponseFromJSONTyped(json, false);
}

export function GetBookStock200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBookStock200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'stock': json['stock'],
        'bookId': json['bookId'],
    };
}

export function GetBookStock200ResponseToJSON(json: any): GetBookStock200Response {
    return GetBookStock200ResponseToJSONTyped(json, false);
}

export function GetBookStock200ResponseToJSONTyped(value?: GetBookStock200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stock': value['stock'],
        'bookId': value['bookId'],
    };
}

