/* tslint:disable */
/* eslint-disable */
/**
 * assignment-template
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Order
 */
export interface Order {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    orderId: string;
    /**
     * Construct a type with a set of properties K of type T
     * @type {{ [key: string]: number; }}
     * @memberof Order
     */
    books: { [key: string]: number; };
    /**
     * 
     * @type {boolean}
     * @memberof Order
     */
    fulfilled: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Order
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the Order interface.
 */
export function instanceOfOrder(value: object): value is Order {
    if (!('orderId' in value) || value['orderId'] === undefined) return false;
    if (!('books' in value) || value['books'] === undefined) return false;
    if (!('fulfilled' in value) || value['fulfilled'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function OrderFromJSON(json: any): Order {
    return OrderFromJSONTyped(json, false);
}

export function OrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Order {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'orderId': json['orderId'],
        'books': json['books'],
        'fulfilled': json['fulfilled'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function OrderToJSON(json: any): Order {
    return OrderToJSONTyped(json, false);
}

export function OrderToJSONTyped(value?: Order | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'orderId': value['orderId'],
        'books': value['books'],
        'fulfilled': value['fulfilled'],
        'createdAt': value['createdAt'].toISOString(),
    };
}

