/* tslint:disable */
/* eslint-disable */
/**
 * assignment-template
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlaceOnShelfBody
 */
export interface PlaceOnShelfBody {
    /**
     * 
     * @type {string}
     * @memberof PlaceOnShelfBody
     */
    bookId: string;
    /**
     * 
     * @type {number}
     * @memberof PlaceOnShelfBody
     */
    numberOfBooks: number;
    /**
     * 
     * @type {string}
     * @memberof PlaceOnShelfBody
     */
    shelf: string;
}

/**
 * Check if a given object implements the PlaceOnShelfBody interface.
 */
export function instanceOfPlaceOnShelfBody(value: object): value is PlaceOnShelfBody {
    if (!('bookId' in value) || value['bookId'] === undefined) return false;
    if (!('numberOfBooks' in value) || value['numberOfBooks'] === undefined) return false;
    if (!('shelf' in value) || value['shelf'] === undefined) return false;
    return true;
}

export function PlaceOnShelfBodyFromJSON(json: any): PlaceOnShelfBody {
    return PlaceOnShelfBodyFromJSONTyped(json, false);
}

export function PlaceOnShelfBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceOnShelfBody {
    if (json == null) {
        return json;
    }
    return {
        
        'bookId': json['bookId'],
        'numberOfBooks': json['numberOfBooks'],
        'shelf': json['shelf'],
    };
}

export function PlaceOnShelfBodyToJSON(json: any): PlaceOnShelfBody {
    return PlaceOnShelfBodyToJSONTyped(json, false);
}

export function PlaceOnShelfBodyToJSONTyped(value?: PlaceOnShelfBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bookId': value['bookId'],
        'numberOfBooks': value['numberOfBooks'],
        'shelf': value['shelf'],
    };
}

