/* tslint:disable */
/* eslint-disable */
/**
 * assignment-template
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShelfStock
 */
export interface ShelfStock {
    /**
     * 
     * @type {string}
     * @memberof ShelfStock
     */
    shelf: string;
    /**
     * 
     * @type {number}
     * @memberof ShelfStock
     */
    count: number;
}

/**
 * Check if a given object implements the ShelfStock interface.
 */
export function instanceOfShelfStock(value: object): value is ShelfStock {
    if (!('shelf' in value) || value['shelf'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function ShelfStockFromJSON(json: any): ShelfStock {
    return ShelfStockFromJSONTyped(json, false);
}

export function ShelfStockFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShelfStock {
    if (json == null) {
        return json;
    }
    return {
        
        'shelf': json['shelf'],
        'count': json['count'],
    };
}

export function ShelfStockToJSON(json: any): ShelfStock {
    return ShelfStockToJSONTyped(json, false);
}

export function ShelfStockToJSONTyped(value?: ShelfStock | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'shelf': value['shelf'],
        'count': value['count'],
    };
}

